### ISSUE TITLE
Vagrant-berkshelf problem

### ISSUE THREAD

**Issue by paulmorriss** [silinternational/addressbook#1]
I had a problem with the berkshelf plugin on vagrant 1.6.5 on Windows. The problem and workaround is described here:
https://github.com/berkshelf/vagrant-berkshelf/issues/227

I dropped that code in the Vagrantfile and it worked.

**Comment by fillup** [comment]
Do you have chef-dk installed? We use chef-dk to get all that setup and haven't had this problem yet.

**Comment by paulmorriss** [comment]
Yes, the line further up
    # Make sure Chef is installed
    config.omnibus.chef_version = :latest
succeeds. It may be that my vagrant is newer than yours. 
P.S. I don't know if you worked it out, but I work for Wycliffe UK.

**Comment by fillup** [comment]
Yeah I recognized your name :-)

config.omnibus.chef_version installs the chef client inside the VM, but not on your host system, and if you're having issues with berkshelf I think it is on your host system that is impacted. So do you have chef-dk installed on your own computer, not the VM? I had issues with berkshef originally too and finally found it works best just to instal chef-dk which comes with all the dependencies needed.

**Comment by paulmorriss** [comment]
I had already installed the Chef DK. When I run chef verify it tells me that chef-dk and berkshelf are verified. Could it be the version of vagrant I'm using with the berkshelf plugin you specify (2.0.1)?

**Comment by fillup** [comment]
Yeah maybe, here are my versions:
- Berkshelf 3.1.5
- Vagrant 1.6.5
- Virtualbox 4.3.20
- vagrant-berkshelf plugin 2.0.1
